### ISSUE TITLE
No results anymore after some time of continuous usage

### ISSUE THREAD

**Issue by akopper** [ahivert/tgtg-python#116]
Awesome piece of software! Love your work. 

When i query the API in a 30s interval for about 2 days, i am not receiving results anymore. 
At that time, with the same account on my phone, from the same network, everything works as expected.

1. Are you aware of any rate-limiting mechanisms on TGTG/Cloudflare side?
2. Are you aware of any workarounds for this?
3. Would it help to run traffic through a proxy with changing IP address?

BR,
Alex

**Comment by ahivert** [comment]
I just published a new release 0.7.0, can you try this one and tell me if it's ok?

**Comment by akopper** [comment]
i'm on it.

**Comment by ahivert** [comment]
Please reopen issue if there is still issue with 0.9.0

**Comment by akopper** [comment]
This problem still persists. 
Items in the response of the api are not the same as in the app after some time. Around one item a day is returned by the api. 

A new login via mail confirmation, without refresh token fixes this. But only for some time.
